name: Run anytime
on:
  schedule:
    - cron: "*/60 * * * *"

jobs:
  blc:
    name: Auto exp
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Run check
      run: |
        pip install requests
        python - <<END
        import requests, sys
        for workflow in requests.get("https://api.github.com/repos/biplobsd/miscActionScripts/actions/workflows/13538553/runs").json()['workflow_runs'][1:]:
          if workflow['status'] == 'in_progress':
            print("Already runing in another workflow job")
            sys.exit(1)
          else:
            print(f"{workflow['run_number']} is not running job")
        END
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install requirements
      run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install requests lxml
    - name: Run script
      run: python3 ./blc/fast_exp.py -m ${{ secrets.MoodleSession }} -u ${{ secrets.username }} -p ${{ secrets.password }} -n --mark -c ${{ secrets.courseLink }}
    
